### ISSUE TITLE
Full Stack projektin katselmointi

### ISSUE THREAD

**Issue by Jakousa** [ankaleh/full-stack-project#1]
# Full Stack projektin katselmointi

Tässä lyhyt katselmointi Full Stack kurssin projektistasi. Katselmoinnissa esitetyt kommentit ovat parannusehdotuksia, joita voit halutessasi ottaa huomioon tässä tai tulevissa projekteissasi. Mitään muutoksia tähän projektiin ei siis ole pakko tehdä suoritusmerkintää varten.

### Mitä tein? ###

Rekisteröidyin

Kirjauduin

Päivitin sivua

Varasin mökin

Lisäsin viestin vieraskirjaan

### Kokemus ###

Hauska projekti! Tällaista tarvitsisi meidänkin perhe. 

Korjaa *heti* salasanakentät type="password"illä.

Saan virheen "Cannot GET /vieraskirja" kun päivitän sivua

Pienempiä juttuja:

Unohdit vaihtaa faviconin ja sivun titlen.

Miksi navbareja on kolme? Ja yksi niistä on tyhjä..

Virhe "passwordConf must be one of the following values: , Ref(password)" ei rekisteröinnin yhteydesä salasanaa kirjoittaessa kerro minulle oikeastaan mistään.

Olisi kiva voida kirjoittaa vieraskirjaan jotain varausta kohti, nyt jouduin muistelemaan mille aikavälille olin varauksen tehnyt.

## Koodi ##

Olet jakanut koodin selkeästi omiin kokonaisuuksiin ja järjestänyt repositorion hyvin. Hienoa työtä. Koodin laatusi on myös hyvää, mutta tässä on muutamia pieniä huomioita ja ajatuksia joita löysin läpikäydessäni:

git on parempi versionhallinnan työkalu kuin kommentit. https://github.com/ankaleh/full-stack-project/blob/7111a3b997713297bdef36c597a49e445d191183/frontend/src/components/AddPost.js#L8

Komponentti https://github.com/ankaleh/full-stack-project/blob/7111a3b997713297bdef36c597a49e445d191183/frontend/src/components/AddPost.js on aika pitkä. Voisikohan sen jakaa pariin pienempään komponenttiin?

Lue https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

Sitä voi käyttää esim tällaisessa tilanteessa https://github.com/ankaleh/full-stack-project/blob/7111a3b997713297bdef36c597a49e445d191183/frontend/src/components/Post.js#L52-L53

muuttamaan logiikkaa hieman selkeämmäksi:

```
const dataInStore = store.readQuery({ query: ALL_POSTS })
if (!dataInStore) return

```

## Kokonaisuus ##

Hieno projekti ja tällaista kelpaa esitellä. Käyttöliittymän puolella oli muutamia ongelmia, joita toivon että jaksat korjata.

**Comment by ankaleh** [comment]
Kiitos palautteesta ja tärkeistä huomautuksista! Olen nyt korjannut sivun päivitykseen liittyvän virheen, vaihtanut favicon.icon, vaihtanut rekisteröitymislomakkeen salasanakenttien tyypin oikeaksi sekä jakanut AddPost-komponentin kahteen pienempään komponenttiin. Navigointipalkkeja on kolme lähinnä esteettisistä syistä (ylimmässä ilmoitukset, keskimmäisessä tiliin liittyvät sivut ja alimmassa sovelluksen muut sivut), mutta näköjään ratkaisuni oli käyttäjän kannalta hämmentävä. :)
